### ISSUE TITLE
Hi, Could you please upload the codes of "Auto-Instruct: Automatic Instruction Generation and Ranking for Black-Box Language Models"

### ISSUE THREAD

**Issue by A11en0** [ytyz1307zzh/Minimally_Edited_Questions#1]
Hi, thanks for your great job on "Auto-Instruct: Automatic Instruction Generation and Ranking for Black-Box Language Models". I am sorry to leave a message on this issue. I couldn't find the source code from the original paper, the page of it is 404. Could you please re-upload the source codes? Thanks!

**Comment by ytyz1307zzh** [comment]
Hi,

Thanks for the interest. The code has been uploaded.
